export const quickFireLies = new Set([
    // `Aged 5, I wrote to Play School to suggest how the BBC should resolve their union conflict.`,
    `I am allergic to coins.`,
    `I fainted in the cinema during Kill Bill.`,
    `When we were first dating, I collected my husband's belly button fluff.`,
    `In a resturant in China, I unwittingly ordered and ate dog.`,
    // `I lost my virginity at 26.`,
    `I have seven cats called Monday, Tuesday, Wednesday, Thursday, Friday, Saturday and Pickle.`,
    `I have been banned from Streatham ice rink.`,
    `I have formulated a five point plan for surviving if I were in prison.`,
    `I have never eaten an apple, not even taken a bite.`,
    `I have no idea how to use a launderette washing machine.`,
    `My parents told me my dog was dead when it was actually in Scunthorpe.`,
    `I killed a falcon playing golf.`,
    `I once pushed a man in a lake for following me shouting Only Me.`,
    `I bunked off school to go to London with a boy called Dick Whittington.`,
    // `I wrote to Jim'll Fix It asking to meet ABBA, they wrote back offering the chance to see how the blue bits were made in cheese.`,
    `I believe disaster will occur if I don't adhere to my special alarm clock system.`,
    `I check for monsters before I go to bed because I'm afraid of the dark.`,
    // `I was voted the 47th sexiest man in Wales.`,
    // `I was voted the 88th sexiest man in the world.`,
    `I have written and published a book of love poems.`,
    `I used to buy my gran a chocalate orange every Christmas until I found seven of them in a draw at her house.`,
    `I have been attacked by a snake charmer and his snake.`,
    `My first word was hoover.`,
    // `I applied for Mastermind with the specialist subject Columbo.`,
    `I used to be a tour guide for a hat museum.`,
    `I once pulled a boy by pretending to be French.`,
    `My parents had to change my name to Lee because I could't pronounce my real name.`,
    `I was a teenage boxer, but I quit because I had a mouth ulcer.`,
    `I have been shopping in Sainsbury's wearing nothing but a trench coat.`,
    `Female admirers used to send me timetables showing when their husbands would be out.`,
    `For six months i cleaned the windows of the Empire State Building.`,
    `When I was little I used to dress myself as an 18th century nobleman.`,
    `I got my head stuck in railings three times in the same week.`,
    // `I got picked on at school because my mother was the dancer in the titles of Tales of the Unexpected.`,
    `For two weeks I drove a car that could only turn left.`,
    `I once picked up a hitchhiker and scared him so much he cried.`,
    `Last year I was ordered to leave Blackpool Tower after I threw a sausage roll off the top.`,
    `As a child at my grandparents' house I had a little bell I would ring if I wanted anything.`,
    `I read Nineteen Eighty-Four from cover to cover in W H Smith, so I didn't have to buy a copy.`,
    `I was thrown out of a nightclub for refusing to stop dancing on top of a table.`,
    `I once put out a fire using my neighbor's milk.`,
    `For six months, I wrote horoscopes for a women's magazine.`,
    `As a child I used to play board games against a bucket with a face painted on it, I called this bucket Stephen Tatlock.`,
    `Last week I actually had to go into a shop and buy four candles.`,
    `I trained for last year's Paris marathon, but pulled out when a doctor advised me that one of my legs is shorter than the other.`,
    `Lost a game of Swing Ball to a chimpanzee.`,
    `When I was 12, I saved up all my pocket money and bought a rowing boat that I never used.`,
    `I can tell the circumference of someone's head just by looking at them.`,
    `Every Sunday, I treat myself to a relaxing bath, with 3 squirts of Fairy Liquid.`,
    `My parents recently forced me to have a new kitchen fitted, because my flat embarrassed them.`,
    // `I once had to show my boss an intimate area of my body to prove why I was late for work.`,
    `I recently bought a cat, but took it back a day later because our personalities clashed.`,
    `I used to try and scare school friends by planting a particular drawing signifying death in their pockets.`,
    `When I'm at home, I amuse myself by shaving only half my face and doing that thing where you have a conversation between two people.`,
    `I once helped my Mum and Dad look for something they'd lost, using a Oujia Board.`,
    `I once paid for some Tapas with a Nissan Micra.`,
    `I can tell if someone is a good dancer just by the way they smile.`,
    `I like pens. And I like to know where my pens are. For this reason, I have a three point pen policy.`,
    `When I'm in a play, as part of my nightly vocal warm-up I perform sets of scales in the voice of a chimpanzee.`,
    `On a wall in my flat there is a mysterious red switch. I have no idea what it does because I have never pressed it and refuse to do so.`,
    `I can break an apple in half with my bare hands.`,
    `I can tell if someone drinks mainly tea or coffee just by listening to (the rumble in) their stomach.`,
    `Last year I was forced to abandon the purchase of a new armchair mid-transaction, because the shop assistant used the terms 'well jel' and 'amazeballs'.`,
    `I once had to abandon my car in a safari park after a baboon climbed through the sunroof, lay down on the back seat and fell asleep.`,
    `One of the codes I live my life by is that my appearance should be in no way noteworthy. But then again, not so unnoteworthy as to be, in itself, noteworthy.`,
    `I once dug up my dead hamster and gave it a wash.`,
    `I can balance a banknote on my nose.`,
]);

export const homeTruths = new Set([
    `I banned my staff from buying paper clips.`,
    `My nickname at school was Ear Sniffer.`,
    `I hosted the British Sausage Awards.`,
    `When I was 23, I had to talk my way out of a fight with a paperboy.`,
    `I recently had an extension built by a builder called Bob.`,
    `I used to proofread dictionaries for a living.`,
    `I was a contestant on Junior MasterChef.`,
    `I have eaten a diamond.`,
    `I can identify any breed of dog just by hearing it growl.`,
    `I once simultaneously worked as both the DJ and the newsreader on local radio using a different accent for each job.`,
    `My nickname at school was Mr. Custard.`,
    `I've been offered £2000 by OK! magazine for pictures of my dog's birthday.`,
    `I have rated 98% on a psychopath test.`,
    `I once worked as part of a circus double act which was called Franko and Tootie.`,
    `I had an interview at MI5 to be a spy.`,
    `I have an identical twin called Jimmy, Jimmy Lives in Canada.`,
    `Kellogg's offered me a job in their development department after I sent them a list of new cereal ideas.`,
    `I have patented a device that stops cats jumping on your lap.`,
    `I have five pigs, all named after my favourite newsreaders.`,
    `For two weeks I drove a car that could only turn left.`,
    `I had an interview at MI5 to be a spy.`,
    `I have been wearing bronzing powder since the age of 12.`,
    `I used to run a market stall that only sold hats to dogs.`,
    `I used to put my underpants on my head to cure my acne.`,
    `I once guessed the exact number of sweets in a Mini Cooper and was awarded a prize by Britain's tallest man.`,
    `I was the first person in the world to breed the Congolese frog Hymenochirus curtipes in captivity.`,
    `I worked as a podium dancer at the Ministry of Sound.`,
    `I once put nail polish remover in my fishtank to give my fish more energy.`,
    `I once had my wallet stolen by a walrus.`,
    `One of my best friends at school was a little man I made from a slice of toast that I always kept in my bag.`,
    `I had a job as a postman but left after a week because I couldn't ride the bike.`,
    `In my garden, I have a life-size statue of myself astride a unicorn.`,
    `I once undertook a self-help course entitled How To Become Taller.`,
    `I once spent an entire day on the Asda shuttle bus just to have a day out.`,
    `Occasionally, as a treat, I put marmite on my face, and let my dog lick it off.`,
    `I always test the temperature of my bath, with my ear.`,
    `I once had a job where I had to answer the phone and say "Hello, beef?".`,
    `I recently had my house exorcised after several weird occurrences spooked me.`,
    `When I was 6 years old I wrote a will after losing a game of Connect4 to my Dad.`,
    `I recite my times tables every night before bed.`,
    `I had a job where we started each day with a motivational song.`,
    `I once found a suitcase and took it to the police station, when they opened it, it contained 34 bunches of bananas.`,
    `As a child, I had so many imaginary friends, we formed an imaginary gang.`,
    `I was so sure that Wombles were real, I used one in an example of a mammal in a GCSE Biology exam.`,
    `I am currently seeing a hypnotist to cure me of my compulsion to visit hypnotists.`,
    `I always make toast by ironing bread, it tastes much better.`,
    `For my first term at University, I rented a bathroom in a Student house and slept in the bathtub every night.`,
    `I am haunted by a recurring dream, in which, I'm a potato.`,
    `I once wet myself in a car and then blamed it on my friends dog.`,
    `I was once driven to A&E in an Ice Cream van; in place of a siren the driver turned on the musical chime.`,
    `I was sacked from my job at a zoo, when my boss found I had been taking photos of the animals weearing hats.`,
    `On Doctors advice I have to sleep in a cycle helmet due to the violent nature of my dreams.`,
    `I've written and have published a triology of romantic novels under female pen name.`,
    `I once prevented a burglar from breaking into my house by hiding behind the door and barking like two different dogs... at him.`,
    `One Christmas morning I woke up stark naked in our shoe cupboard clutching nothing but two cans of fake snow.`,
    `Every time I shower I must adhere to my strict system for drying myself.`,
    `As a child, rather than sleeping with a comfort blanket or teddy bear, I slept with a potato.`,
    `For three days running I accidentally ate cat food for dinner.`,
    `I cannot go on airport travelators. The one and only time I did, I got so freaked out by how super-humanly fast I was walking that I had to be taken to the sick bay to calm down.`,
    `When I want to remember something late at night, instead of writing it down I just grab an object from my bedside table and throw it across the room.`,
    `I used to write and hand in homework for an imaginary class-mate.`,
    `When I travel by Tube I like to see how many strangers I can make yawn by yawning myself. My record is nine in one carriage.`,
    `At school, I invented a game called Snorkel Parka Music Practice Room.`,
    `When I was younger I was regularly paid to babysit Marvin, my neighbour's pet dog, who had died and been stuffed.`,
    `When I'm feeling tired I photograph myself to see how tired I look. I then compare this photograph with other photographs I've taken of myself when I felt tired to see how tired I really am.`,
    `In nightclubs, in order to impress the ladies, I used to break into my special catwalk move.`,
    `I once got a tattoo because I was told that it would disappear after three years.`,
    `I once set fire to my house with a box of fireworks.`,
    `When I'm stressed I take a water-free bath.`,
]);